define([
  './homepage.config',
  'common/utils/registerToModule',
  './banner.list',
  './banner.edit',
  './atlas.list',
  './atlas.edit',
  './notice.list',
  './notice.edit',
  './newscount.list',
  './newscount.edit',
  './newscate.list',
  './newscate.edit',
  './card.list',
  './card.edit',
  './hotword.list',
  './hotword.edit',
  './funny.list',
  './funny.edit',
  './funnysrc.list',
  './funnysrc.edit',
  './pictureCate.list',
  './pictureCate.edit',
  './picture.list',
  './pictureSubject.list',
  './pictureSubject.edit',
  './JPNews.list',
  './JPNews.edit',
  './JPNewsSubCate.list',
  './JPNewsSubCate.edit',
  './JPNewsCate.list',
  './JPNewsCate.edit',
  './JPNewsSource.list',
  './JPNewsSource.edit',
  './pictureSource.list',
  './pictureSource.edit'
], function(homepageConfig, rtm, BannerListCtrl,BannerEditCtrl,AtlasListCtrl,AtlasEditCtrl,
            NoticeListCtrl,NoticeEditCtrl,NewscountListCtrl,NewscountEditCtrl,NewscateListCtrl,
            NewscateEditCtrl,CardListCtrl,CardEditCtrl,HotwordListCtrl,HotwordEditCtrl,FunnyListCtrl,
            FunnyEditCtrl,FunnysrcListCtrl,FunnysrcEditCtrl,PictureCateListCtrl,PictureCateEditCtrl,
            PictureListCtrl,PictureSubjectListCtrl,PictureSubjectEditCtrl,JPNewsListCtrl,JPNewsEditCtrl,
            JPNewsSubCateListCtrl,JPNewsSubCateEditCtrl,JPNewsCateListCtrl,JPNewsCateEditCtrl,
            JPNewsSourceListCtrl,JPNewsSourceEditCtrl,PictureSourceListCtrl,PictureSourceEditCtrl) /*invoke*/ {
  var modName = 'app.homepage',
    mod = angular.module(modName, []);
  rtm(BannerListCtrl,BannerEditCtrl,AtlasListCtrl,AtlasEditCtrl,NoticeListCtrl,NoticeEditCtrl,
      NewscountListCtrl,NewscountEditCtrl,NewscateListCtrl,NewscateEditCtrl,CardListCtrl,CardEditCtrl,
      HotwordListCtrl,HotwordEditCtrl,FunnyListCtrl,FunnyEditCtrl,FunnysrcListCtrl,FunnysrcEditCtrl,
      PictureCateListCtrl,PictureCateEditCtrl,PictureListCtrl,PictureSubjectListCtrl,PictureSubjectEditCtrl,
      JPNewsListCtrl,JPNewsEditCtrl,JPNewsSubCateListCtrl,JPNewsSubCateEditCtrl,JPNewsCateListCtrl,
      JPNewsCateEditCtrl,JPNewsSourceListCtrl,JPNewsSourceEditCtrl,PictureSourceListCtrl,PictureSourceEditCtrl)(mod);

  homepageConfig(mod);
  return modName;
});
