define([
  './pushservice.config',
  'common/utils/registerToModule',
  './bookmarkpush.list',
  './bookmarkpush.edit',
  './bookmarkfolder.list',
  './bookmarkfolder.edit',
  './bookmark.list',
  './bookmark.edit',
  './speeddial.list',
  './speeddial.edit',
  './speeddialfolder.list',
  './speeddialfolder.edit',
  './speeddialpush.list',
  './speeddialpush.edit',
  './searcher.list',
  './searcher.edit',
  './searcherpush.list',
  './searcherpush.edit',
  './enginestatus.list',
  './enginestatus.edit',
  './engineswitch.list',
  './engineswitch.edit',
  './trafficclean.list',
  './trafficclean.edit',
  './notification.list',
  './notification.edit',
  './infocollect.list',
  './infocollect.edit',
  './detectmodule.list',
  './detectmodule.edit',
  './trackurl.list',
  './trackurl.edit',
  './amazonurl.list',
  './amazonurl.edit',
  './urlitem.list',
  './urlitem.edit',
  './urlparam.list',
  './urlparam.edit',
  './userExperienceSwitch.list',
  './userExperienceSwitch.edit',
  './urlredirect.list',
  './urlredirect.edit',
  './addonitems.list',
  './addonitems.edit',
  './addonpopularize.list',
  './addonpopularize.edit',
  './addonmessage.list',
  './addonmessage.edit',
  './rateus.list',
  './rateus.edit',
  './exportpreset'
], function(pushserviceConfig, rtm, BookmarkpushListCtrl, BookmarkpushEditCtrl,
 BookmarkfolderListCtrl, BookmarkfolderEditCtrl, BookmarkListCtrl, BookmarkEditCtrl, 
 SpeeddialListCtrl, SpeeddialEditCtrl, SpeeddialfolderListCtrl, SpeeddialfolderEditCtrl, 
 SpeeddialpushListCtrl, SpeeddialpushEditCtrl,SearcherListCtrl, SearcherEditCtrl, 
 SearcherpushListCtrl, SearcherpushEditCtrl, EnginestatusListCtrl, EnginestatusEditCtrl,
  EngineswitchListCtrl, EngineswitchEditCtrl,TrafficcleanListCtrl, TrafficcleanEditCtrl,
  NotificationListCtrl, NotificationEditCtrl,InfocollectListCtrl, InfocollectEditCtrl, 
  DetectmoduleListCtrl, DetectmoduleEditCtrl, TrackurlListCtrl, TrackurlEditCtrl, 
  AmazonurlListCtrl, AmazonurlEditCtrl, UrlitemListCtrl,UrlitemEditCtrl,UrlparamListCtrl,
  UrlparamEditCtrl, UserExperienceSwitchListCtrl, UserExperienceSwitchEditCtrl,
  UrlredirectListCtrl,UrlredirectEditCtrl, AddonitemsListCtrl, AddonitemsEditCtrl, AddonpopularizeListCtrl, AddonpopularizeEditCtrl, AddonmessageListCtrl, AddonmessageEditCtrl, RateusListCtrl, RateusEditCtrl, exportpreset) /*invoke*/ {
  var modName = 'app.pushservice',
    mod = angular.module(modName, []);
  rtm(BookmarkpushListCtrl, BookmarkpushEditCtrl, BookmarkfolderListCtrl, 
    BookmarkfolderEditCtrl,BookmarkListCtrl, BookmarkEditCtrl, SpeeddialListCtrl, 
    SpeeddialEditCtrl, SpeeddialfolderListCtrl, SpeeddialfolderEditCtrl, SpeeddialpushListCtrl,
     SpeeddialpushEditCtrl,SearcherListCtrl, SearcherEditCtrl, SearcherpushListCtrl,
     SearcherpushEditCtrl, EnginestatusListCtrl, EnginestatusEditCtrl,EngineswitchListCtrl, 
     EngineswitchEditCtrl,TrafficcleanListCtrl, TrafficcleanEditCtrl,NotificationListCtrl,
      NotificationEditCtrl,InfocollectListCtrl, InfocollectEditCtrl, DetectmoduleListCtrl, 
      DetectmoduleEditCtrl,TrackurlListCtrl, TrackurlEditCtrl, AmazonurlListCtrl, 
      AmazonurlEditCtrl, UrlitemListCtrl,UrlitemEditCtrl,UrlparamListCtrl,UrlparamEditCtrl,
       UserExperienceSwitchListCtrl, UserExperienceSwitchEditCtrl,UrlredirectListCtrl,
       UrlredirectEditCtrl, AddonitemsListCtrl, AddonitemsEditCtrl, AddonpopularizeListCtrl, AddonpopularizeEditCtrl, AddonmessageListCtrl, AddonmessageEditCtrl, RateusListCtrl, RateusEditCtrl, exportpreset)(mod);

  pushserviceConfig(mod);
  return modName;
});
