define([
  './apiService',
  'common/utils/registerToModule',
  './aosoperator',
  './aospackage',
  './aosruledata',
  './aossource',
  './aoslocale',
  './bookmarkpush',
  './bookmarkfolder',
  './bookmark',
  './speeddial',
  './speeddialfolder',
  './icon',
  './speeddialpush',
  './searcher',
  './searcherpush',
  './enginestatus',
  './engineswitch',
  './trafficclean',
  './notification',
  './infocollect',
  './detectmodule',
  './trackurl',
  './amazonurl',
  './urlitem',
  './urlparam',
  './iamazonurl',
  './iurlitem',
  './iurlparam',
  './exportpreset',
  './usermanagement',
  './promotionspeeddial',
  './promotionurl',
  './iapppush',
  './iurloption',
  './iurloptionfolder',
  './ispeeddial',
  './ispeeddialfolder',
  './ispeeddialpush',
  './ibookmark',
  './pcbookmark',
  './ibookmarkfolder',
  './ibookmarkpush',
  './pcbookmarkpush',
  './isearcher',
  './isearcherpush',
  './ipromotionurl',
  './userExperienceSwitch',
  './iostrackurl',
  './urlredirect',
  './addonitems',
  './addonpopularize',
  './addonmessage',
  './rateus',
  './addondownloadurl',
  './rateusoptimization',
  './rateusoptimizationweight',
  './addonvideoinfo',
  './dolphinwidgeturl',
  './intervalfunc'
], function(apiService, rtm, aosoperator, aospackage, aosruledata, aossource, aoslocale, bookmarkpush, bookmarkfolder,bookmark, speeddial, speeddialfolder, icon, speeddialpush, searcher, searcherpush, enginestatus, engineswitch, trafficclean,notification,infocollect,detectmodule,trackurl
,amazonurl,urlitem,urlparam,iamazonurl,iurlitem,iurlparam,exportpreset,usermanagement,promotionspeeddial,promotionurl,iapppush,iurloption,iurloptionfolder,ispeeddial,ispeeddialfolder,ispeeddialpush,ibookmark,pcbookmark,ibookmarkfolder,ibookmarkpush,pcbookmarkpush,isearcher,ipromotionurl,
isearcherpush,userExperienceSwitch,iostrackurl,urlredirect,addonitems,addonpopularize,addonmessage,rateus,addondownloadurl,rateusoptimization,rateusoptimizationweight,addonvideoinfo,dolphinwidgeturl,intervalfunc) /*invoke*/ {
  var modName = 'app.ds',
    mod = angular.module(modName, []);
  rtm(apiService, aosoperator, aospackage, aosruledata, aossource, aoslocale, bookmarkpush, bookmarkfolder,bookmark, speeddial, speeddialfolder, icon, speeddialpush, searcher, searcherpush, enginestatus, engineswitch, trafficclean,notification,infocollect,detectmodule,trackurl,
    amazonurl,urlitem,urlparam,iamazonurl,iurlitem,iurlparam,exportpreset,usermanagement,promotionspeeddial,promotionurl,iapppush,iurloption,iurloptionfolder,ispeeddial,ispeeddialfolder,ispeeddialpush,ibookmark,pcbookmark,ibookmarkfolder,ibookmarkpush,pcbookmarkpush,isearcher,
    ipromotionurl,isearcherpush,userExperienceSwitch,iostrackurl,urlredirect,addonitems,addonpopularize,addonmessage,rateus,addondownloadurl,rateusoptimization,rateusoptimizationweight,addonvideoinfo,dolphinwidgeturl,intervalfunc)(mod);

  return modName;
});
