define([
  './ipushservice.config',
  'common/utils/registerToModule',
  './urloption.list',
  './urloption.edit',
  './urloptionfolder.list',
  './urloptionfolder.edit',
  './apppush.list',
  './apppush.edit',
  './speeddial.list',
  './speeddial.edit',
  './speeddialfolder.list',
  './speeddialfolder.edit',
  './speeddialpush.list',
  './speeddialpush.edit',
  './bookmark.list',
  './bookmark.edit',
  './bookmarkfolder.list',
  './bookmarkfolder.edit',
  './bookmarkpush.list',
  './bookmarkpush.edit',
  './searcher.list',
  './searcher.edit',
  './searcherpush.list',
  './searcherpush.edit',
  './promotionurl.list',
  './promotionurl.edit',
  './amazonurl.list',
  './amazonurl.edit',
  './urlitem.list',
  './urlitem.edit',
  './urlparam.list',
  './urlparam.edit',
  './iamazonurl.list',
  './iamazonurl.edit',
  './iurlitem.list',
  './iurlitem.edit',
  './iurlparam.list',
  './iurlparam.edit',
  './iostrackurl.list',
  './iostrackurl.edit'
], function(ipushserviceConfig, rtm, UrloptionListCtrl, UrloptionEditCtrl,UrloptionfolderListCtrl, 
  UrloptionfolderEditCtrl, ApppushListCtrl, ApppushEditCtrl,iSpeeddialListCtrl, iSpeeddialEditCtrl, 
  iSpeeddialfolderListCtrl, iSpeeddialfolderEditCtrl, iSpeeddialpushListCtrl, iSpeeddialpushEditCtrl,
  iBookmarkListCtrl,iBookmarkEditCtrl,iBookmarkfolderListCtrl,iBookmarkfolderEditCtrl,iBookmarkpushListCtrl,
  iBookmarkpushEditCtrl,iSearcherListCtrl,iSearcherEditCtrl,iSearcherpushListCtrl,iSearcherpushEditCtrl,
  PromotionurlListCtrl,PromotionurlEditCtrl, AmazonurlListCtrl, AmazonurlEditCtrl, UrlitemListCtrl,
  UrlitemEditCtrl,UrlparamListCtrl,UrlparamEditCtrl, iAmazonurlListCtrl, iAmazonurlEditCtrl, 
  iUrlitemListCtrl,iUrlitemEditCtrl,iUrlparamListCtrl,iUrlparamEditCtrl,IostrackurlListCtrl, IostrackurlEditCtrl) /*invoke*/ {
  var modName = 'app.ipushservice',
    mod = angular.module(modName, []);
  rtm(UrloptionListCtrl, UrloptionEditCtrl,UrloptionfolderListCtrl, UrloptionfolderEditCtrl, 
    ApppushListCtrl, ApppushEditCtrl, iSpeeddialListCtrl,iSpeeddialEditCtrl, iSpeeddialfolderListCtrl, 
    iSpeeddialfolderEditCtrl, iSpeeddialpushListCtrl, iSpeeddialpushEditCtrl,iBookmarkListCtrl,
    iBookmarkEditCtrl,iBookmarkfolderListCtrl,iBookmarkfolderEditCtrl,iBookmarkpushListCtrl,
    iBookmarkpushEditCtrl,iSearcherListCtrl,iSearcherEditCtrl,iSearcherpushListCtrl,iSearcherpushEditCtrl,
    PromotionurlListCtrl,PromotionurlEditCtrl, AmazonurlListCtrl, AmazonurlEditCtrl, UrlitemListCtrl,
    UrlitemEditCtrl,UrlparamListCtrl,UrlparamEditCtrl, iAmazonurlListCtrl, iAmazonurlEditCtrl, 
    iUrlitemListCtrl, iUrlitemEditCtrl, iUrlparamListCtrl, iUrlparamEditCtrl,IostrackurlListCtrl, IostrackurlEditCtrl)(mod);

  ipushserviceConfig(mod);
  return modName;
});
